quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:6379
quarkus.redis.max-pool-size=50
quarkus.redis.max-waiting-handlers=1024

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://10.98.223.137