apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voting-frontend
  name: voting-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: voting-frontend
    spec:
      containers:
      - image: pbhaggblom/voting-frontend:v6.1
        name: voting-frontend
        ports:
        - containerPort: 80
        resources: {}
status: {}
